version: '3.8'

services:
  web:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: absencesdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
